list:
    limit_generated_excerpt: false
    limit_generated_char_excerpt: 360
    limit_generated_sentence_excerpt: 3
    list_per_page: 3
    index_max_posts: 3
sort:
    limit_generate_title: 3
nav:
    limit_item_lines: 3
about:
    socialNetwork:
        github: 'https://github.com/zhao-robert'
        twitter: 'https://twitter.com/yan_mind' 
    avatar: https://avatars.githubusercontent.com/u/52877222?v=4 
    self_instro: This is zhao-robert.
colors: 
    theme_color:
        light:
        dark:
    background_color:
        light:
        dark:
    text_color:
        light:
        dark:
    selected_text_backgroundColor:
        light: 
        dark: 
    selected_text_color:
        light:
        dark:
    quote_block_background_color:
        light:
        dark:
    code_block_background_color:
        light:
        dark:
fonts:
    main_fonts:
    monospace_fonts: